# Generated by Django 4.1 on 2022-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tomtat',
            field=models.CharField(max_length=500),
        ),
    ]
