# Generated by Django 4.1 on 2022-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0003_article_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
