# Generated by Django 4.1 on 2022-11-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',)},
        ),
    ]
