# Generated by Django 4.1 on 2022-11-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.TextField(default='image1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.TextField(default='image2'),
            preserve_default=False,
        ),
    ]
