# Generated by Django 4.1 on 2022-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0006_article_image1_article_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.TextField()),
                ('url', models.TextField()),
                ('url_type', models.CharField(choices=[('facebook', 'fab fa-facebook text-gray-300 text-lg md:text-xl'), ('github', 'fab fa-github mr-1')], max_length=100)),
                ('url_name', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[(1, 'President'), (2, 'Vice President'), (3, 'Project Leader'), (4, 'Head of Pr'), (5, 'Head of Events'), (6, 'Head of Medes')], max_length=100)),
            ],
        ),
    ]
