# Generated by Django 4.1 on 2022-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0007_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='position',
            field=models.CharField(choices=[('1', 'President'), ('2', 'Vice President'), ('3', 'Project Leader'), ('4', 'Head of Pr'), ('5', 'Head of Events'), ('6', 'Head of Medes')], max_length=100),
        ),
    ]
