# Generated by Django 4.1 on 2022-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0008_alter_core_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Project Leader', 'Project Leader'), ('Head of Pr', 'Head of Pr'), ('Head of Events', 'Head of Events'), ('Head of Medes', 'Head of Medes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='core',
            name='url_type',
            field=models.CharField(choices=[('fab fa-facebook text-gray-300 text-lg md:text-xl', 'facebook'), ('fab fa-github mr-1', 'github')], max_length=100),
        ),
    ]
