# Generated by Django 4.1 on 2022-11-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_template', '0009_alter_core_position_alter_core_url_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='core',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='core',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
