# Generated by Django 4.1 on 2022-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAWeb', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tomtat',
            new_name='content',
        ),
    ]
